angular
  .module('flugel.components',[
    'flugel.components.keyboard',
    'flugel.components.tokenScreen',
    'flugel.components.longpress',
    'flugel.components.tokenManagement',
    'flugel.components.manageServices',
    'flugel.components.selectionRole',
    'flugel.components.charts',
    'flugel.components.sidenav'
  ]);
